new build

diff --git a/build/Empty Trash.app/Contents/Resources/script b/build/Empty Trash.app/Contents/Resources/script
--- a/build/Empty Trash.app/Contents/Resources/script
+++ b/build/Empty Trash.app/Contents/Resources/script
@@ -1,4 +1,18 @@
 #!/bin/sh
 
+# empty_trash.sh
+# Empty the trash directories on OS X without the Item in Use block
+# Copyright 2015 Christopher Simpkins
+# MIT License
+
 rm -rf ~/.Trash
+
+if (( $? )); then
+	echo "ALERT:Failed to empty ~/.Trash"
+fi
+
 rm -rf /Volumes/*/.Trashes
+
+if (( $? )); then
+	echo "ALERT:Failed to empty /Volumes/*/.Trashes"
+fi
